name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/run-tox.yaml
    with:
      python-version: "3.13"
      tox-env: lint

  check:
    name: Check
    uses: ./.github/workflows/run-tox.yaml
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: check

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

  test:
    name: Unit tests
    uses: ./.github/workflows/run-tox.yaml
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: coverage
    
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

  integration-test:
    name: Integration tests
    uses: ./.github/workflows/run-tox.yaml
    with:
      python-version: "3.13"
      tox-env: integration-tests
      env-args: -vv --db=${{ matrix.database }}

    strategy:
      matrix:
        database:
          - mssql
          - mysql
          - oracle
          - postgresql
      fail-fast: false
