name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@a66638ef339967bc8099ab93e648f85852de2c28 # v.0.0.2
    with:
      python-version: "3.14"
      tox-env: lint

  check:
    name: Check
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@a66638ef339967bc8099ab93e648f85852de2c28 # v.0.0.2
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: check

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

  test:
    name: Unit tests
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@a66638ef339967bc8099ab93e648f85852de2c28 # v.0.0.2
    with:
      python-version: ${{ matrix.python-version }}
      tox-env: coverage

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

  integration-test:
    name: Integration tests
    uses: albertodonato/github-workflows/.github/workflows/run-tox.yaml@a66638ef339967bc8099ab93e648f85852de2c28 # v.0.0.2
    with:
      python-version: "3.14"
      tox-env: integration-tests
      env-args: -vv --db=${{ matrix.database }}

    strategy:
      matrix:
        database:
          - mssql
          - mysql
          - oracle
          - postgresql
      fail-fast: false
