name: Run Tox

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: The Python version to use
        required: true
      tox-env:
        type: string
        description: Name of the tox environment to run
        required: true
      env-args:
        type: string
        description: Optional arguments for the tox environment
        required: false
      artifact-path:
        type: string
        description: Path to upload as artifact
        required: false
      artifact-name:
        type: string
        description: Name for the artifact to upload (only used if a path is specified)
        required: false

jobs:
  run-tox:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install tox
        run: |
          pip install --upgrade pip tox

      - name: Run environment 
        run: |
          tox run -e ${{ inputs.tox-env }} -- ${{ inputs.env-args }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact-path != '' }}
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
