name: Run Tox

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      tox-env:
        required: true
        type: string
      env-args:
        required: false
        type: string

jobs:
  run-tox:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install tox
        run: |
          pip install --upgrade pip tox

      - name: Run environment 
        run: |
          tox run -e ${{ inputs.tox-env }} -- ${{ inputs.env-args }}
